### ISSUE TITLE
Provide Documentation for Apt Plugin

### ISSUE THREAD

**Issue by dsburns** [microsoft/do-client#114]
How is the apt plugin supposed to be used with Azure device update?  Does it require a custom lists file in /etc/apt?  Are users supposed to implement a Debian package repository in the cloud for this plugin to work with?

**Comment by shishirb-MSFT** [comment]
The apt plugin, once installed, starts handling all http/https downloads initiated by APT. The default http transport gets replaced with ours. There is no custom lists file needed unless you want to download packages hosted on non-default package repositories.

Regarding documentation - thanks for asking. We will take a look and enhance documentation where needed. @cmknox FYI.

**Comment by dsburns** [comment]
@shishirb-MSFT Thanks for the response.  I guess I don't understand the use case for this.  If you're using an OS like Ubuntu, the functionality seems redundant.  What does using the DO client to download Debian packages from archives provide over using the standard Debian package tools?
