### ISSUE TITLE
After installation and configuration of du-config.json Apt-get update no longer works on Ubuntu 18.04 server VM

### ISSUE THREAD

**Issue by SillyKeith** [microsoft/do-client#122]
**Issue:** After setting up a fresh Ubuntu Server 18.04 VM and installing Edge 1.3(or 1.2.10) & Device Update (that uses Microsoft Identity Service),  apt-get update will hang and no longer work.   

The delivery optimization logs show that the original ubuntu sources domains are replaced with my iothub domain name.
```
2022-07-19T00:27:05.4968525Z 7948  7952           {GetHost} Returning MCC host: [**---my iot hub domain---**] for original host: [us.archive.ubuntu.com]
2022-07-19T00:27:05.4968612Z 7948  7952  info     {_UpdateConnectionTypeAndGetUrl} 040e59e2-a6cc-424d-bf68-71f76ccfa279, connection type: 1, numAttempts: 1, url: http://**---my iot hub domain name--**-/ubuntu/dists/bionic-security/restricted/i18n/by-hash/SHA256/b70f67be66800195bcaff6e758ae3108ee009022d055925ff2faefe7c25123b8?cacheHostOrigin=us.archive.ubuntu.com
```

**Repro Steps:**

Windows 11 + Hyper-V 
Create a new VM Gen 2 (secureboot off)
Install Ubuntu Server 18.04  - defaults taken everywhere.

**Install MS Repo Source & Key**
1.	curl https://packages.microsoft.com/config/ubuntu/18.04/multiarch/prod.list > ./microsoft-prod.list
2.	sudo cp ./microsoft-prod.list /etc/apt/sources.list.d/
3.	curl https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor > microsoft.gpg
4.	sudo cp ./microsoft.gpg /etc/apt/trusted.gpg.d/
5.	wget https://packages.microsoft.com/config/ubuntu/18.04/multiarch/packages-microsoft-prod.deb -O packages-microsoft-prod.deb
6.	sudo dpkg -i packages-microsoft-prod.deb
7.	rm packages-microsoft-prod.deb

**Install  Moby-engine**
1.	sudo apt-get update
2.	sudo apt-get install moby-engine
3.	sudo vim /etc/docker/daemon.json
4.	Add the below info to daemon.json.
{
        "dns": ["1.1.1.1", "8.8.8.8"],
        "log-driver": "json-file",
        "log-opts": {
                "max-size": "10m",
                "max-file": "3"
        }
}
5.	sudo systemctl restart docker

**Install Edge (this gets the LATEST which at this time is 1.3)** 
1.	sudo apt-get update
2.	sudo apt-get install aziot-edge defender-iot-micro-agent-edge
3.	sudo iotedge config mp --connection-string "<insert your Primary Key>"
4.	sudo iotedge config apply
5.	sudo iotedge system status

**Take a VM snapshot so you can revert easily**

**Install Device Update for IoT Hub**
1.	sudo apt-get update
2.	sudo apt-get install deviceupdate-agent deliveryoptimization-plugin-apt
3.	sudo vim /etc/adu/du-config.json
4.	Input the below and save
{
  "schemaVersion": "1.0",
  "aduShellTrustedUsers": [
    "adu",
    "do"
  ],
  "manufacturer": "FakeOEM",
  "model": "Ubuntu1804VM",
  "agents": [
    {
      "name": "main",
      "runas": "adu",
      "connectionSource": {
        "connectionType": "AIS",
        "connectionData": ""
      },
      "manufacturer": "FakeOEM",
      "model": "Ubuntu1804VM"
    }
  ]
}

5	sudo systemctl restart adu-agent
6.	sudo systemctl status adu-agent  --	Validate it's running.
7.	sudo apt-get update
8.	<HANG OBSERVED>

[do-agent.20220718_213415.log](https://github.com/microsoft/do-client/files/9144273/do-agent.20220718_213415.log)
[du-agent.20220718-213528.log](https://github.com/microsoft/do-client/files/9144274/du-agent.20220718-213528.log)

**Comment by shishirb-MSFT** [comment]
This should be mitigated with #125. Contacting the GatewayHostName will still be attempted but DO agent will fall back to the original source quickly.
