### ISSUE TITLE
Are versions being tracked properly

### ISSUE THREAD

**Issue by dsburns** [microsoft/do-client#128]
If you compare git tags for v0.8.2 with 0.6.0, you can see there are changes to the client-lite library.  However, the client-lite project version is still 0.6.0 which results in the debian packge versions being set to this value.  Shouldn't the client-lite CMake version change if the code changes?

**Comment by shishirb-MSFT** [comment]
For deliveryoptimization-agent debian package, looking at the control file:
releases/tag/v0.6.0 has Version: 0.4.0
releases/tag/v0.8.2 has Version: 0.6.0

Can you clarify the question?

**Comment by shishirb-MSFT** [comment]
The debian package version has indeed changed between git tags v0.6.0 and v0.8.2. I just now built both tags (see below).

$ git checkout tags/v0.6.0
...
HEAD is now at b40eeac Fix bootstrap script
$ python3 ./build/build.py --project agent --package-for DEB
...
...
CPack: - package: /tmp/build-deliveryoptimization-agent/linux-debug/**deliveryoptimization-agent_0.4.0_amd64.deb** generated.
$ git log -n 1
commit b40eeacb275e3323257f5398dbb1be56ae2318e1 (HEAD, **tag: v0.6.0**)

$ git checkout tags/v0.8.2
Previous HEAD position was b40eeac Fix bootstrap script
HEAD is now at ef70c5c Update gitHubConnection in release pipeline (merge #109)
$ python3 ./build/build.py --project agent --package-for DEB --clean
...
CPack: - package: /tmp/build-deliveryoptimization-agent/linux-debug/**deliveryoptimization-agent_0.6.0_amd64.deb** generated.
$ git log -n 1
commit ef70c5c8a59d46820c648f434249516957966e7f (HEAD, **tag: v0.8.2**, origin/main, origin/HEAD, user/shishirb/fix-iotconnstring-mcc)

**Comment by dsburns** [comment]
I apologize.  I was confusing the git tag version with the ADU device update repo.  You are correct, the debian package version does change with the changes in git tags.  Thanks for clarifying this!
