### ISSUE TITLE
build/boostrap.sh lacks execute permissions and has several errors on Ubuntu 20.04

### ISSUE THREAD

**Issue by oottka** [microsoft/do-client#58]
When cloning and building the project on a fresh Ubuntu 20.04 VM, the [build/boostrap.sh](https://github.com/microsoft/do-client/blob/main/build/bootstrap.sh) script has several issues. Steps to reproduce:

- Create a new Ubuntu 20.04 VM
- Clone the project
- Run `./build/boostrap.sh --platform ubuntu2004`

The script has the following issues:

- [The documentation](https://github.com/microsoft/do-client#development-machine-setup) tells to run `cd build/boostrap`. This is obviously wrong.
- The script does not have execute permissions (need to do chmod u+x before it can be run)
- After setting execute permissions and running the script, the following error is thrown:
```
-- websocketpp not found, using the embedded version
CMake Error at /usr/lib/x86_64-linux-gnu/cmake/Boost-1.71.0/BoostConfig.cmake:117 (find_package):
  Could not find a package configuration file provided by "boost_thread"
  (requested version 1.71.0) with any of the following names:

    boost_threadConfig.cmake
    boost_thread-config.cmake

  Add the installation prefix of "boost_thread" to CMAKE_PREFIX_PATH or set
  "boost_thread_DIR" to a directory containing one of the above files.  If
  "boost_thread" provides a separate development package or SDK, be sure it
  has been installed.
Call Stack (most recent call first):
  /usr/lib/x86_64-linux-gnu/cmake/Boost-1.71.0/BoostConfig.cmake:182 (boost_find_component)
  /usr/share/cmake-3.16/Modules/FindBoost.cmake:443 (find_package)
  Release/cmake/cpprest_find_boost.cmake:49 (find_package)
  Release/cmake/cpprest_find_websocketpp.cmake:17 (cpprest_find_boost)
  Release/src/CMakeLists.txt:68 (cpprest_find_websocketpp)


-- Configuring incomplete, errors occurred!
```
This can be fixed by installing libboost-thread-dev.
- After installing libboost-thread-dev and re-running the script, the following error is thrown:
```
Package python-pip is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source
However the following packages replace it:
  python3-pip

E: Package 'python-pip' has no installation candidate
```
This is because python-pip no longer exists in Ubuntu 20.04, it being replaced by python3-pip. This can be fixed by modifying the script to install python3-pip on Ubuntu instead.

**Comment by shishirb-MSFT** [comment]
Ubuntu 20.04 support is available now with v0.8.2. Please open a new issue if there are any problems.
